class Registro
{
    public int? TP_NOT { get; set; }
    public string? ID_AGRAVO { get; set; }
    public int? DT_NOTIFIC { get; set; }
    public int? SEM_NOT { get; set; }
    public int? NU_ANO { get; set; }
    public int? SG_UF_NOT { get; set; }
    public int? ID_MUNICIP { get; set; }
    public double? ID_REGIONA { get; set; }
    public double? ID_UNIDADE { get; set; }
    public string? DT_SIN_PRI { get; set; }
    public int? SEM_PRI { get; set; }
    public double? ANO_NASC { get; set; }
    public int? NU_IDADE_N { get; set; }
    public string? CS_SEXO { get; set; }
    public double? CS_GESTANT { get; set; }
    public double? CS_RACA { get; set; }
    public double? CS_ESCOL_N { get; set; }
    public int? SG_UF { get; set; }
    public double? ID_MN_RESI { get; set; }
    public double? ID_RG_RESI { get; set; }
    public double? ID_PAIS { get; set; }
    public string? DT_INVEST { get; set; }
    public string? ID_OCUPA_N { get; set; }
    public double? FEBRE { get; set; }
    public double? MIALGIA { get; set; }
    public double? CEFALEIA { get; set; }
    public double? EXANTEMA { get; set; }
    public double? VOMITO { get; set; }
    public double? NAUSEA { get; set; }
    public double? DOR_COSTAS { get; set; }
    public double? CONJUNTVIT { get; set; }
    public double? ARTRITE { get; set; }
    public double? ARTRALGIA { get; set; }
    public double? PETEQUIA_N { get; set; }
    public double? LEUCOPENIA { get; set; }
    public double? LACO { get; set; }
    public double? DOR_RETRO { get; set; }
    public double? DIABETES { get; set; }
    public double? HEMATOLOG { get; set; }
    public double? HEPATOPAT { get; set; }
    public double? RENAL { get; set; }
    public double? HIPERTENSA { get; set; }
    public double? ACIDO_PEPT { get; set; }
    public double? AUTO_IMUNE { get; set; }
    public string? DT_CHIK_S1 { get; set; }
    public string? DT_CHIK_S2 { get; set; }
    public string? DT_PRNT { get; set; }
    public double? RES_CHIKS1 { get; set; }
    public double? RES_CHIKS2 { get; set; }
    public double? RESUL_PRNT { get; set; }
    public string? DT_SORO { get; set; }
    public double? RESUL_SORO { get; set; }
    public string? DT_NS1 { get; set; }
    public double? RESUL_NS1 { get; set; }
    public string? DT_VIRAL { get; set; }
    public double? RESUL_VI_N { get; set; }
    public string? DT_PCR { get; set; }
    public double? RESUL_PCR_ { get; set; }
    public double? SOROTIPO { get; set; }
    public double? HISTOPA_N { get; set; }
    public double? IMUNOH_N { get; set; }
    public double? HOSPITALIZ { get; set; }
    public string? DT_INTERNA { get; set; }
    public double? UF { get; set; }
    public double? MUNICIPIO { get; set; }
    public double? TPAUTOCTO { get; set; }
    public double? COUFINF { get; set; }
    public double? COPAISINF { get; set; }
    public double? COMUNINF { get; set; }
    public double? CLASSI_FIN { get; set; }
    public double? CRITERIO { get; set; }
    public double? DOENCA_TRA { get; set; }
    public double? CLINC_CHIK { get; set; }
    public double? EVOLUCAO { get; set; }
    public string? DT_OBITO { get; set; }
    public string? DT_ENCERRA { get; set; }
    public double? ALRM_HIPOT { get; set; }
    public double? ALRM_PLAQ { get; set; }
    public double? ALRM_VOM { get; set; }
    public double? ALRM_SANG { get; set; }
    public double? ALRM_HEMAT { get; set; }
    public double? ALRM_ABDOM { get; set; }
    public double? ALRM_LETAR { get; set; }
    public double? ALRM_HEPAT { get; set; }
    public double? ALRM_LIQ { get; set; }
    public string? DT_ALRM { get; set; }
    public double? GRAV_PULSO { get; set; }
    public double? GRAV_CONV { get; set; }
    public double? GRAV_ENCH { get; set; }
    public double? GRAV_INSUF { get; set; }
    public double? GRAV_TAQUI { get; set; }
    public double? GRAV_EXTRE { get; set; }
    public double? GRAV_HIPOT { get; set; }
    public double? GRAV_HEMAT { get; set; }
    public double? GRAV_MELEN { get; set; }
    public double? GRAV_METRO { get; set; }
    public double? GRAV_SANG { get; set; }
    public double? GRAV_AST { get; set; }
    public double? GRAV_MIOC { get; set; }
    public double? GRAV_CONSC { get; set; }
    public double? GRAV_ORGAO { get; set; }
    public string? DT_GRAV { get; set; }
    public double? MANI_HEMOR { get; set; }
    public double? EPISTAXE { get; set; }
    public double? GENGIVO { get; set; }
    public double? METRO { get; set; }
    public double? PETEQUIAS { get; set; }
    public double? HEMATURA { get; set; }
    public double? SANGRAM { get; set; }
    public double? LACO_N { get; set; }
    public double? PLASMATICO { get; set; }
    public double? EVIDENCIA { get; set; }
    public double? PLAQ_MENOR { get; set; }
    public double? CON_FHD { get; set; }
    public double? COMPLICA { get; set; }
    public double? TP_SISTEMA { get; set; }
    public double? NDUPLIC_N { get; set; }
    public string? DT_DIGITA { get; set; }
    public double? CS_FLXRET { get; set; }
    public double? FLXRECEBI { get; set; }
    public double? MIGRADO_W { get; set; }

}