class Registro
{
    public string? t15_id { get; set; }
    public string? t15_descricao { get; set; }
    public string? t15_tipo { get; set; }
    public double? t15_kmAtual { get; set; }
    public string? t15_latitude { get; set; }
    public string? t15_longitude { get; set; }
    public string? t15_dataHora { get; set; }
    public string? t15_obsMotorista { get; set; }
    public string? t15_romaneio_id { get; set; }
    public string? t15_data_registro { get; set; }
    public string? t15_entrega_id { get; set; }
    public string? t15_motivo_devol_reent_id { get; set; }
    public string? t15_usuario_responsavel { get; set; }
    public string? t02_descricao { get; set; }
    public string? t32_seq_pedido_erp { get; set; }
    public string? t32_valor { get; set; }
    public double? t32_peso { get; set; }
    public double? t32_volume_m3 { get; set; }
    public string? t32_nf { get; set; }
    public string? t05_codigo_erp { get; set; }
    public string? t05_codigo_erp_aj1 { get; set; }
    public string? t05_codigo_erp_aj2 { get; set; }
    public string? t05_codigo_erp_aj3 { get; set; }
    public string? t05_codigo_erp_aj4 { get; set; }
    public string? t10_carga_formada_erp { get; set; }
    public string? t06_codigo_erp { get; set; }
    public string? t06_placa { get; set; }
    public string? t44_codigo_erp { get; set; }
    public string? t15_link_foto { get; set; }
    public string? descricao_motivo_devol_reent { get; set; }
    public string? codigo_erp_motivo_devol_reent { get; set; }
    public double? peso_agendado { get; set; }
    public string? t166_descricao { get; set; }
    public string? t166_medida { get; set; }
    public string? t32_numero_recibo_coleta { get; set; }
    public int? t32_qtd_informado { get; set; }
    public double? t32_qtd_volume_informado_coleta { get; set; }
    public string? t32_serie_nf { get; set; }
    public string? t43_codigo_filial_erp { get; set; }
    public double? peso_coletado { get; set; }
}
